version: '3'
services:
  jekyll-server:
    image: jekyll/jekyll:4.2.2
    container_name: jekyll-setup
    environment:
      MY_ENV_VAR_DUMMY: 'dummy'
    volumes:
      - '../.:/srv/jekyll'
    ports:
      - 4000:4000 # (localhost port) => (docker port)
    command: "jekyll new ./new_site"